# Dependencies
markdown:		  kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'GuvBlog'
description:      'Words about technology'
url:              http://dblv.github.io/

author:
  name:           'Will Jacobs'
  url:            https://twitter.com/willtheguvnor

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/DblV/DblV.github.io