# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'GuvBlog'
description:      'Words about technology'
url:              http://dblv.github.io/

author:
  name:           'Will Jacobs'
  url:            https://twitter.com/_DblV_

paginate:         5

excerpt_separator: <!--end_excerpt-->

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/DblV/DblV.github.io